spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/springexample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate

